### PR TITLE
Continuous integration with GitHub Actions

### LINKED ISSUE #95: Build on GitHub Actions
Enable [GitHub Actions](https://github.com/features/actions) for this project. You will need to install the development version of usethis (`remotes::install_dev("usethis")`. For more details see [GitHub Actions for R](https://github.com/r-lib/actions/tree/master/examples).

- [ ] run `usethis::use_github_actions_tidy()`
  - [ ] Add badges in your clipboard to [README.md](../blob/master/README.md)
    - If `README.Rmd` exists add badges to that instead and run `devtools::build_readme()`.
- [ ] look at existing [.travis.yml](../blob/master/.travis.yml) and see if there is extra logic that needs to be included.
  - If `.travis.yml` builds a pkgdown site 
    - [ ] run `usethis::use_github_action("pkgdown.yaml")`
    - [ ] ping @jimhester to add `DEPLOY_PAT` to the repository secrets. 
- [ ] look at existing [appveyor.yml](../blob/master/appveyor.yml) and see if there is extra logic from `.travis.yml` and `appveyor.yml` that needs to be included.
- [ ] modify [R-CMD-check.yaml](../blob/.github/workflows/R-CMD-check.yaml) with extra logic if needed.
- [ ] ping @jimhester to add codecov.io token `CODECOV_TOKEN` to the repository secrets.

### PR DESCRIPTION
**Pull request by mitchelloharawild**
Resolves #95

### CODE REVIEW

**Comment by mitchelloharawild** [comment]
This seems to work? I can't fully test as I don't have the secrets :key:

**Comment by mitchelloharawild** [comment]
@jennybc 
The secret `GOOGLESHEETS4_PASSWORD` should be set, and `GOOGLESHEETS4_NOAUTH` should be left unset.

**Comment by jimhester** [comment]
@jennybc you can merge this whenever you have the secrets set and you are ready.

**Comment by jennybc** [comment]
We are DELETING `.travis.yml` and `appveyor.yaml`, i.e. going cold turkey as we do this? Without ever seeing a successful check + pkgdown build? I'm basically 100% sure there are going to be some issues to iron out here.

I thought we'd have some period of leaving what works "in place", as we sort out the gh actions stuff.

**Comment by jennybc** [comment]
I've added the `GOOGLESHEETS4_PASSWORD` secure env var.

But my instinct is to restore the travis and appveyor config and to omit the pkgdown action at first. Merge. See successful R CMD checks. Then add the pkgdown action.

Thoughts @jimhester?

**Comment by jimhester** [comment]
No, deleting those files was not what we were doing in other repos, we should revert those changes.

**Comment by jennybc** [comment]
OK I'll edit this PR accordingly and proceed with my more conservative plan.

**Comment by jennybc** [comment]
Thanks @mitchelloharawild! I'm going to pursue this in smaller increments, but I'm about to merge the R CMD check part of this and will bring back the pkgdown build once I've got that working.

**Comment by mitchelloharawild** [comment]
Thanks for working on a great package :bee:

**Pull request merged**
